name: simplehttp
description: A dart library used for making a simple HTTP server.

  This should be used for testing purposes and not for real production.

  As you can see in the example it's still bare bones.
version: 0.0.3
homepage: https://github.com/Emrage/simplehttp

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
